spring:
  # 设置druid数据源
  datasource:
    # 数据源基本配置
    #    url: jdbc:mysql://192.168.0.150:3306/mybatis_plus?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    #    driver‐class‐name: com.mysql.cj.jdbc.Driver # 注意MySQL8.x的驱动
    #    username: root
    #    password: aaaaaa
    #    type: com.alibaba.druid.pool.DruidDataSource
    #p6spy
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.0.150:3306/mybatis_plus?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: aaaaaa
    druid:
      filters: stat,wall # druid数据源需要屏蔽其防火墙

# mybatis-plus配置（与mybatis配置项几乎一样，就是这里用mybatis-plus而不是mybatis）
# 可配置项见官网 https://mybatis.plus/config/#globalconfig-2
mybatis-plus:
  type-aliases-package: com.haoqian.mybatisPlus.entity # 开启器@Alias别名功能注解的支持
  type-enums-package: com.haoqian.mybatis_plus.myEnum  # 枚举类型包扫描
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志打印(支持配置文件和注解)
    map-underscore-to-camel-case: true # 驼峰下划线映射规则（默认true）
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler # 默认枚举类型处理器
  global-config:
    db-config:
      id-type: auto      # 全局主键生成策略
      table-prefix: tbl_ # 全局表前缀配置

      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略类属上配置 @TableLogic)
      logic-delete-value: 1        # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0    # 逻辑未删除值(默认为 0)

# 设置actuator健康管理
management:
  endpoints:
    web:
      exposure:
        include: "*"   # 设置开启所有监控端点（使用/httptrace还需注册HttpTraceRepository实例）
  endpoint:
    health:
      show-details: always # 设置显示健康状态的详细信息